 <nav class="navigation">
                    <ul>
                        <li>
                        <img src="images/mlp_logo.png" alt= "club logo">
                        
                            <a href="index.php">Home</a>
                            <a href="events.php">Past Events</a>
                        <h1>Entrepreneurship at University of Rochester</h1>
                        </li>
                    </ul>
                </nav>